
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."feed_type" AS ENUM (
    'ATTENDANCE',
    'PHOTO',
    'PROMOTION',
    'ACTIVITY'
);

ALTER TYPE "public"."feed_type" OWNER TO "postgres";

CREATE TYPE "public"."route_status" AS ENUM (
    'IN_PROGRESS',
    'FINISHED',
    'WAITING_TO_START',
    'PAUSED'
);

ALTER TYPE "public"."route_status" OWNER TO "postgres";

CREATE TYPE "public"."states_check_in_out" AS ENUM (
    'CHECK_IN',
    'CHECK_OUT',
    'ABSENT'
);

ALTER TYPE "public"."states_check_in_out" OWNER TO "postgres";

CREATE TYPE "public"."user_types" AS ENUM (
    'PARENT',
    'STAFF',
    'DRIVER'
);

ALTER TYPE "public"."user_types" OWNER TO "postgres";

CREATE TYPE "public"."waypoint_status" AS ENUM (
    'FINISHED',
    'IN_PROGRESS',
    'WAITING_TO_START',
    'PAUSED'
);

ALTER TYPE "public"."waypoint_status" OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  insert into public.users (id)
  values (new.id);
  return new;
end;
$$;

ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."address_list" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "order" integer,
    "latitude" double precision,
    "longitude" double precision,
    "routeId" "uuid",
    "studentId" "uuid",
    "status" "public"."waypoint_status"
);

ALTER TABLE "public"."address_list" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."check_in_out" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "state" "public"."states_check_in_out" NOT NULL,
    "userIdState" "uuid",
    "dateState" "date",
    "timeState" time without time zone,
    "studentId" "uuid"
);

ALTER TABLE "public"."check_in_out" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."configs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "defaultVanPhoto" "text",
    "defaultUsePphoto" "text",
    "phoneNumbermanager" "text"
);

ALTER TABLE "public"."configs" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."events" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text",
    "image" "text",
    "link" "text",
    "date" "date"
);

ALTER TABLE "public"."events" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."kidFeeds" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" "public"."feed_type" NOT NULL,
    "dateTime" timestamp without time zone,
    "studentId" "uuid",
    "photoName" "text",
    "text" "text" NOT NULL,
    "creatorId" "uuid"
);

ALTER TABLE "public"."kidFeeds" OWNER TO "postgres";

ALTER TABLE "public"."kidFeeds" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."feeds_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."kids_schedule" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "monday" boolean,
    "tuesday" boolean,
    "wednesday" boolean,
    "thursday" boolean,
    "friday" boolean,
    "student" "uuid"
);

ALTER TABLE "public"."kids_schedule" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."message" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "senderId" "text" NOT NULL,
    "receiverIds" "text" NOT NULL,
    "content" "text" NOT NULL,
    "sentAt" timestamp without time zone NOT NULL,
    "isRead" boolean
);

ALTER TABLE "public"."message" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."pictures" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "picture" "text",
    "studentId" "uuid"
);

ALTER TABLE "public"."pictures" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."route" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "date" "text",
    "departTime" "text",
    "lat" double precision,
    "lng" double precision,
    "driver" "text",
    "helper" "text",
    "route" "json",
    "vanId" "uuid",
    "status" "public"."route_status",
    "currentDestination" "text",
    "finishedTime" "text"
);

ALTER TABLE "public"."route" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."students" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "parent1Email" "text",
    "parent2Email" "text",
    "dropoffAddress" "text",
    "lat" double precision,
    "lng" double precision,
    "birthdate" "date",
    "photo" "text",
    "parent1Id" "uuid",
    "parent2Id" "uuid",
    "vanId" "uuid",
    "routeId" "uuid",
    "checkedIn" boolean,
    "lastCheckIn" timestamp without time zone,
    "currentStateId" "uuid",
    "notes" "text",
    "allergies" "text",
    "medicine" "text"
);

ALTER TABLE "public"."students" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "sub" "text",
    "name" "text",
    "email" "text",
    "unitNumber" "text",
    "address" "text",
    "lng" double precision,
    "lat" double precision,
    "phoneNumber" "text",
    "userType" "text",
    "photo" "text",
    "pushToken" "text",
    "updated_at" timestamp with time zone
);

ALTER TABLE "public"."users" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."van" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text",
    "image" "text",
    "plate" "text",
    "model" "text",
    "year" integer,
    "seats" integer,
    "boosterSeats" integer
);

ALTER TABLE "public"."van" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."week_day_routes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "date" "date",
    "weekday" "text",
    "vanId" "uuid",
    "studentId" "uuid",
    "Order" "text",
    "studentName" "text",
    "studentDropOffAddress" "text"
);

ALTER TABLE "public"."week_day_routes" OWNER TO "postgres";

ALTER TABLE ONLY "public"."address_list"
    ADD CONSTRAINT "address_list_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."check_in_out"
    ADD CONSTRAINT "check_in_out_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."configs"
    ADD CONSTRAINT "configs_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."kidFeeds"
    ADD CONSTRAINT "feeds_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."kids_schedule"
    ADD CONSTRAINT "kids_schedule_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."message"
    ADD CONSTRAINT "message_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."pictures"
    ADD CONSTRAINT "pictures_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."route"
    ADD CONSTRAINT "route_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."students"
    ADD CONSTRAINT "students_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_sub_key" UNIQUE ("sub");

ALTER TABLE ONLY "public"."van"
    ADD CONSTRAINT "van_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."week_day_routes"
    ADD CONSTRAINT "week_day_routes_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."address_list"
    ADD CONSTRAINT "fk_route_addresslist" FOREIGN KEY ("routeId") REFERENCES "public"."route"("id");

ALTER TABLE ONLY "public"."students"
    ADD CONSTRAINT "fk_route_students" FOREIGN KEY ("routeId") REFERENCES "public"."route"("id");

ALTER TABLE ONLY "public"."address_list"
    ADD CONSTRAINT "fk_student_addresslist" FOREIGN KEY ("studentId") REFERENCES "public"."students"("id");

ALTER TABLE ONLY "public"."check_in_out"
    ADD CONSTRAINT "fk_student_checkinout" FOREIGN KEY ("studentId") REFERENCES "public"."students"("id");

ALTER TABLE ONLY "public"."kids_schedule"
    ADD CONSTRAINT "fk_student_kidsschedule" FOREIGN KEY ("student") REFERENCES "public"."students"("id");

CREATE POLICY "Allow authencated users to ALL" ON "public"."address_list" TO "authenticated" USING (true);

CREATE POLICY "Allow authencated users to ALL" ON "public"."check_in_out" TO "authenticated" USING (true);

CREATE POLICY "Allow authencated users to ALL" ON "public"."configs" TO "authenticated" USING (true);

CREATE POLICY "Allow authencated users to ALL" ON "public"."events" TO "authenticated" USING (true);

CREATE POLICY "Allow authencated users to ALL" ON "public"."kids_schedule" TO "authenticated" USING (true);

CREATE POLICY "Allow authencated users to ALL" ON "public"."message" TO "authenticated" USING (true);

CREATE POLICY "Allow authencated users to ALL" ON "public"."pictures" TO "authenticated" USING (true);

CREATE POLICY "Allow authencated users to ALL" ON "public"."route" TO "authenticated" USING (true);

CREATE POLICY "Allow authencated users to ALL" ON "public"."students" TO "authenticated" USING (true);

CREATE POLICY "Allow authencated users to ALL" ON "public"."users" TO "authenticated" USING (true);

CREATE POLICY "Allow authencated users to ALL" ON "public"."van" TO "authenticated" USING (true);

CREATE POLICY "Allow authencated users to ALL" ON "public"."week_day_routes" TO "authenticated" USING (true);

CREATE POLICY "Allow authenticad users to all" ON "public"."kidFeeds" TO "authenticated" USING (true);

ALTER TABLE "public"."address_list" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."check_in_out" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."configs" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."events" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."kidFeeds" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."kids_schedule" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."message" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."pictures" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."route" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."students" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."van" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."week_day_routes" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."kidFeeds";

ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."message";

ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."students";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";

GRANT ALL ON TABLE "public"."address_list" TO "anon";
GRANT ALL ON TABLE "public"."address_list" TO "authenticated";
GRANT ALL ON TABLE "public"."address_list" TO "service_role";

GRANT ALL ON TABLE "public"."check_in_out" TO "anon";
GRANT ALL ON TABLE "public"."check_in_out" TO "authenticated";
GRANT ALL ON TABLE "public"."check_in_out" TO "service_role";

GRANT ALL ON TABLE "public"."configs" TO "anon";
GRANT ALL ON TABLE "public"."configs" TO "authenticated";
GRANT ALL ON TABLE "public"."configs" TO "service_role";

GRANT ALL ON TABLE "public"."events" TO "anon";
GRANT ALL ON TABLE "public"."events" TO "authenticated";
GRANT ALL ON TABLE "public"."events" TO "service_role";

GRANT ALL ON TABLE "public"."kidFeeds" TO "anon";
GRANT ALL ON TABLE "public"."kidFeeds" TO "authenticated";
GRANT ALL ON TABLE "public"."kidFeeds" TO "service_role";

GRANT ALL ON SEQUENCE "public"."feeds_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."feeds_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."feeds_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."kids_schedule" TO "anon";
GRANT ALL ON TABLE "public"."kids_schedule" TO "authenticated";
GRANT ALL ON TABLE "public"."kids_schedule" TO "service_role";

GRANT ALL ON TABLE "public"."message" TO "anon";
GRANT ALL ON TABLE "public"."message" TO "authenticated";
GRANT ALL ON TABLE "public"."message" TO "service_role";

GRANT ALL ON TABLE "public"."pictures" TO "anon";
GRANT ALL ON TABLE "public"."pictures" TO "authenticated";
GRANT ALL ON TABLE "public"."pictures" TO "service_role";

GRANT ALL ON TABLE "public"."route" TO "anon";
GRANT ALL ON TABLE "public"."route" TO "authenticated";
GRANT ALL ON TABLE "public"."route" TO "service_role";

GRANT ALL ON TABLE "public"."students" TO "anon";
GRANT ALL ON TABLE "public"."students" TO "authenticated";
GRANT ALL ON TABLE "public"."students" TO "service_role";

GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";

GRANT ALL ON TABLE "public"."van" TO "anon";
GRANT ALL ON TABLE "public"."van" TO "authenticated";
GRANT ALL ON TABLE "public"."van" TO "service_role";

GRANT ALL ON TABLE "public"."week_day_routes" TO "anon";
GRANT ALL ON TABLE "public"."week_day_routes" TO "authenticated";
GRANT ALL ON TABLE "public"."week_day_routes" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
