import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
  container: {
    justifyContent: "center",
    alignItems: "center",
    paddingTop: Platform.OS === "android" ? 25 : 0,
    padding: 10,
  },
  header: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    padding: 0,
  },
  headerGreetings: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  title: {
    fontSize: 24,
    marginTop: 20,
    fontWeight: "bold",
    marginBottom: 10,
  },
  headerButtons: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    marginTop: 10,
  },
  chatButton: {
    //flex: 1,
    width: 80,
    alignItems: "center",
    backgroundColor: "blue",
    borderRadius: 10,
    paddingVertical: 20,
    //paddingHorizontal: 10,
    marginHorizontal: 5,
  },
  checkInButton: {
    //flex: 1,
    width: 80,
    alignItems: "center",
    backgroundColor: "green",
    borderRadius: 10,
    paddingVertical: 20,
    //paddingHorizontal: 10,
    marginHorizontal: 5,
  },
  activityButton: {
    //flex: 1,
    width: 80,
    alignItems: "center",
    backgroundColor: "orange",
    borderRadius: 10,
    paddingVertical: 20,
    // paddingHorizontal: 10,
    marginHorizontal: 5,
  },
  studentsButton: {
    //flex: 1,
    width: 80,
    alignItems: "center",
    backgroundColor: "red",
    borderRadius: 10,
    paddingVertical: 20,
    // paddingHorizontal: 10,
    marginHorizontal: 5,
  },
  pickUpButton: {
    //flex: 1,
    width: 80,
    alignItems: "center",
    backgroundColor: "brown",
    borderRadius: 10,
    paddingVertical: 20,
    // paddingHorizontal: 10,
    marginHorizontal: 5,
  },
  buttonText: {
    color: "white",
    fontSize: 12,
    marginTop: 5,
  },
  messageCountBadge: {
    backgroundColor: "red",
    borderRadius: 20,
    position: "absolute",
    top: -8,
    right: -6,
    padding: 4,
  },
  messageCountText: {
    color: "white",
    fontSize: 15,
    paddingHorizontal: 5,
  },
});
